services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: MyOrder
      MONGO_INITDB_ROOT_PASSWORD: TeamD3v
    volumes:
      - mongo_pos_data:/data/db
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pos-backend
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://MyOrder:TeamD3v@mongo:27017/pos?authSource=admin
      - CLIENT_URL=http://localhost:4201

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pos-client
    ports:
      - "4201:4200"
    depends_on:
      - server

volumes:
  mongo_pos_data:
